### ISSUE TITLE
Documentation on `default databases` clarification

### ISSUE THREAD

**Issue by webRat** [markbates/pop#10]
> Default databases are lowercase, underscored versions of the struct name. Examples: User{} is "users", FooBar{} is "foo_bars", etc...

So, should this read `lowercased, plural, underscored versions of the struct name`? Your example above says `User{}` becomes `users` and FooBar{} becomes `foo_bars`. Or is this `User{}` becomes `user` and `FooBar{}` becomes `foo_bar`

Thanks.

**Comment by markbates** [comment]
I should read "plural". A PR would be great. :)
