### ISSUE TITLE
soda pg migrate change_column to uuid fails

### ISSUE THREAD

**Issue by mkozjak** [markbates/pop#107]
Using `change_column("stores", "item_id", "uuid", {})` gives

```
error inside of calling function: error executing migrations/20170728222040_foreign_keys_to_uuid.up.fizz, sql: ALTER TABLE "stores" ALTER COLUMN "item_id" TYPE UUID, ALTER COLUMN "item_id" SET NOT NULL;
```

where item_id was an int and I'd like to change it to uuid type.

Running generated query against pg through psql:
```
ALTER TABLE "stores" ALTER COLUMN "item_id" TYPE UUID, ALTER COLUMN "item_id" SET NOT NULL;
ERROR:  column "item_id" cannot be cast automatically to type uuid
HINT:  You might need to specify "USING item_id::uuid".
```

The instructed command doesn't work per se:
```
ALTER TABLE "stores" ALTER COLUMN "item_id" TYPE UUID USING item_id::uuid;

ERROR:  cannot cast type integer to uuid
LINE 1: ...OLUMN "item_id" TYPE UUID USING item_id::uuid;
```

Whereas this works:
```
CREATE EXTENSION "uuid-ossp";
ALTER TABLE "stores" ALTER COLUMN "item_id" SET DATA TYPE UUID USING (uuid_generate_v4());
```

So this fizz works:
```
raw('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
raw('ALTER TABLE "stores" ALTER COLUMN "item_id" SET DATA TYPE UUID USING (uuid_generate_v4());')
```

So, should we just raw sql in fizz for this?

**Comment by markbates** [comment]
Yeah, that's a bit out of scope of fizz. I would either use `raw` or a use a `.sql` file instead of fizz.

**Comment by mkozjak** [comment]
Btw, is there any fizz to sql converter out?

**Comment by markbates** [comment]
You can run the migrations with -d which prints out the sql. You could also dig into the fizz packages and run it. It's actually pretty easy. The magic happens here https://github.com/markbates/pop/blob/master/fizz/bubbler.go

-----------
Mark Bates
