### ISSUE TITLE
[feature] new cache?

### ISSUE THREAD

**Issue by u007** [markbates/pop#109]
Hi @markbates ,

do you think its a good idea to implement cache for finder?
cache can be implement to use either by:

- cloning struct (faster, but doesn't support clustering) or;
- storing it onto redis using json
- both mechanism (having first option as local cache, and redis as shared)

but it also mean that for 2nd and 3rd option, next step is to expires local and redis cache when someone updated or delete the record using pop.Connection by using publish and subscribe

what is your opinion on this? shall redis be the only option?

thanks

------------
later phase, perhaps its possible to cache also based on where clauses, joins, group by, having and selected fields which can be complicated

**Comment by markbates** [comment]
I don't think this is a particularly good idea. First, caching is incredibly hard to get right, especially cache invalidation. I think we could end up chasing our tails a lot on that and no-one would be particularly happy. Caching, in my opinion, should be left to a 3rd party library, service, etc... that the user has complete control over.

**Comment by u007** [comment]
Cant we do this with a flag on/off?


best regards,
James
Merc Studio Dot Com
eMail: james@mercstudio.com
www: www.mercstudio.com
