### ISSUE TITLE
Custom field type possible?

### ISSUE THREAD

**Issue by ruqqq** [markbates/pop#111]
Is there any way to register custom type as a field? For e.g.  I have a field with both its name and type called `location` but in db it'll be recorded in the field called location of string type.

**Comment by markbates** [comment]
Yes. Custom types in Go must implement both the sql.Scanner interface, https://golang.org/pkg/database/sql/#Scanner, and the driver.Valuer interface, https://golang.org/pkg/database/sql/driver/#Value
