### ISSUE TITLE
c.ValidateAndSave error classification

### ISSUE THREAD

**Issue by mkozjak** [markbates/pop#117]
We should be able to somehow dissect specific errors other than just strings. If I'm using this correctly, the only way of getting an error is in a string format.

ie. I want to control a `c.ValidateAndSave` failure when unique constraint (duplicate key) appears.
All I currently get is `pq: duplicate key value violates unique constraint "someconstraint"` whether I try using
```
switch err := errors.Cause(err).(type) {
        ...
}
```

or whatever else.

I'd expect an error to maybe have a `Class` method (or something like that) which would tell me the error is classified as `uniqueContraintDuplication` or whatever (in a single word). Is such thing possible at all?

Thanks in advance!

**Comment by markbates** [comment]
That's really a question for the `pq` package I think, since they're the ones returning that error.

I usually try to put a validation in my code so I don't hit that type of error:

```go
func (u *User) Validate(tx *pop.Connection) (*validate.Errors, error) {
	var err error
	return validate.Validate(
		&validators.StringIsPresent{Field: u.Email, Name: "Email"},
		&validators.StringIsPresent{Field: u.PasswordHash, Name: "PasswordHash"},
		// check to see if the email address is already taken:
		&validators.FuncValidator{
			Field:   u.Email,
			Name:    "Email",
			Message: "%s is already taken",
			Fn: func() bool {
				var b bool
				q := tx.Where("email = ?", u.Email)
				if u.ID != uuid.Nil {
					q = q.Where("id != ?", u.ID)
				}
				b, err = q.Exists(u)
				if err != nil {
					return false
				}
				return !b
			},
		},
	), err
}
```

**Comment by mkozjak** [comment]
Thanks for the example!

**Comment by mkozjak** [comment]
@markbates If I set Message to "uniqueConstraintViolation" I get "uniqueConstraintViolation%!(EXTRA string=foo)".
Why the part with the percentage? I know my field from the outside already.

If I set it like you to "uniqueConstraintViolation %s" I get it with "uniqueConstraintViolation foo", but I'd still need to parse that...
