### ISSUE TITLE
Proposal of mysql driver and improving ConnectionDetails (and configuration format)

### ISSUE THREAD

**Issue by sio4** [markbates/pop#120]
Hello @markbates and others,

While I worked on MySQL connection problem regarding to URL parsing now a days, I've found something to be improved about `ConnectionDetails` structure and configuration format.

First, in perspective of the users, I think `ConnectionDetails.URL` and corresponding configuration (`env.url`) is very useful for fine configurations since it is flexible and extensible (e.g. detail options). To simplify to configure, even if the developer is not familiar to the database or its driver, it is better that the URL format is really unified. (but currently, SQLite doesn't support it and the format of Postgres and MySQL is different.)

Next, but sometimes, including now, we need to support some driver specific format of data source location indicator. even if it is URL format or not.

So I propose two things.

**First one is changing(unifying) URL format** (For this, I influenced from subversion's URL format)

From:
> `dialect://user:pass@host:port/database?option1=value1&option2=value2`

To:
> `dialect+protocol://user:pass@host:port/database?opt1=val1&opt2bool`

Example for this is:
> `postgres+tcp://user:pass@host/database` (for TCP protocol and default port)
> `postgres://user:pass@host:port/database` (for default TCP and custom port)
> `mysql+socket:///tmp/mysql.sock` (for UNIX socket)
> `sqlite:///tmp/database.sqlite` (for full path)
> `sqlite+file://database/dev.sqlite` (for relative path)

With this, we can figure out not just the dialect, but also protocol and it is easy for parsing (as we already have even though the options part is not implemented yet.)

**Second thing I proposing is adding a new field to `ConnectionDetails` structure called `DSN`**, to hold driver specific (not uniform) format of the data source location. (so the user can configure the connection with their understanding of underlying driver or can copy from other references easily.)

With this two, we can make a configuration routine like that:

```
Parse the configuration file as is. (by `config.go`)
IF DSN is given with Dialect:
    Use it directly for connection (as second argument to `sqlx.Open` in `connection.go`)
ELSE IF URL is given:
    Parse it and (in `connection_details.go` but without `switch` for dialect) [A]
    Use parsed values for generating DSN (by `driver adapter` like `mysql.go`) [B]
ELSE IF other values are given:
    Use this values for generating DSN (same as above) [B]
```

How do you think about this?

In fact, Today I tried to integrate [ziutek/mymysql](https://github.com/ziutek/mymysql) to `pop` but it uses so different format of DSN. It it not hard job itself but I think this situation can be happen again when we want to support new database or data backend. Then how many `case` for `switch` on `connection.go` and `connection_details.go` we need? IMO, current `connection_details.go` and `Finalize()` has limitation for this.

I always THANKS for nice POP! (and Buffalo too!)

**Comment by markbates** [comment]
Here's the use case I absolutely don't want to break. I set up an application on something like Heroku, they automatically set a `DATABASE_URL` ENV var that looks something like this:

```
DATABASE_URL:          postgres://user:pass@ec2-12-345-567-890.compute-1.amazonaws.com:5432/db
```

Right now, when I deploy, the default `database.yml` file works just fine for me right out of the box. 

How do your proposed changes affect that? Breaking that compatibility is a non-starter. So anything that breaks that won't work.

**Comment by sio4** [comment]
Yes, I don't want to break that. Contrary, What I want to do is using this cool intuitive URL format more widely for all drivers. (See second line of my example.  This is that form of URL)

For eample, In case of MySQL on Heroku, it also uses same format of URL. But the said thing is, this URL is not compatible with underlying driver's DSN so the issue #116 is occurred.

Currently, CD.URL() just returns URL from conf or Env but what sqlx.Open() what is not URL but driver specific DSN.
So what I want to say is that we need to check the current workflow and condition then make unified way for the URL to DSN conversion as driver adapter's method not as connection_details's switch/cases.

For the more, for users who want to use DSN not URL for fine tuning, or some future drivers not fit to URL style of configuration, adding DSN field is helpful I think.

Sorry to my poor English.
If you agree with using same URL form for all drivers is good, and giving users flexible ways to configure is also good, then I will try to show it as code.

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
