### ISSUE TITLE
Can I adapt additional mysql driver (which is not have "driver: bad connection")

### ISSUE THREAD

**Issue by sio4** [markbates/pop#121]
Hi,
Can I add additional driver for MySQL to POP?
The target driver is [ziutek/mymysql](https://github.com/ziutek/mymysql), another mysql driver support `database/sql`.

While I write test codes for my current project using `buffalo`, and `suite` also, I faced strange issue of current MySQL driver: "`driver: bad connection`". (It mostly occurred as "`bad connection`" but sometimes "`invalid connection`" anyway.) If I run `buffalo test` several times, almost 50% of the run meet this issue.

I tried to find the answer for this issue by googling but failed. There is many issues with same error from several years before, but the driver contains this issue yet :-( So I tried to find another driver and I found this `mymysql` driver and quickly integrated to POP, and It works fine without that issue. (I mentioned about this integration on #120, the proposal for the connection details structure.)

So my question is,

1. Can I add additional driver for MySQL which is already supported by `go-sql-driver/mysql`?
   * I mean not exchange. just add another driver for the same database.
   * If I added this, the name of dialect will be `mymysql` by following the name of the driver.
2. This driver does not support multi-statements query. Is there any rules for the requirement?
   * So I tested with modified version of `TruncateAll()` of adapter.
   * I found the `soda migrate` also uses multi statements queries. So if I integrate it, this part also need to be checked or changed or...
   * I think, Especially using query builder, the multi-statements query is not common or... not exists except testing and migration process.

Please tell me how can I do for this.

**Comment by markbates** [comment]
Adding a new driver isn't an easy task. It needs to support all of the existing functionality, not just in pop, but also soda and fizz.

**Comment by sio4** [comment]
Yes, I agree.
In fact, I don't want to add this driver at the first time but I want to find some solution for the "bad connection" issue within this set of packages.

Finally I found the only solution, another driver, and tested with that driver. Anyway did you ever hear similar issue? 

Fortunately, since the database it self is same and most part of the existing code can be shared or reused I guess.

I already mostly finished pop side tonight and working fine with existing app code. Soda (and migration) need to be checked with multi statements issue if you give me an agreement. Fizz is... I think can be shared because it based on same database but need to check the structure to find it sharable or not.

Anyway current driver seems not fit for production. I need some solution for it... T.T

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
