### ISSUE TITLE
Wondering way using CLI for db creation and others

### ISSUE THREAD

**Issue by sio4** [markbates/pop#122]
Hello,
Is there any reason using execution of command line client instead of using API for create database, drop database and some other tasks?

https://github.com/markbates/pop/blob/9e3f577a6ef58a6c412fb1cf6fae7a6e24689113/mysql.go#L62

https://github.com/markbates/pop/blob/9e3f577a6ef58a6c412fb1cf6fae7a6e24689113/postgresql.go#L78

**Comment by markbates** [comment]
Because it was the quickest way to "get to market". I'd love to not have to use command line clients, if you want to take a stab at making the commands work without the clients.

**Comment by sio4** [comment]
OK, I will try it soon for MySQL first.
I wrote this issue because when I enabled a Travis-CI for my project, the `buffalo db create` is not working. The reason why is that the `-p` option of the `mysql` client is password but if there is no following (pass)word, it means 'show me the prompt'. Since Travis-CI's mysql password is blank, the command line part of the POP is not working.

Thanks.

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
