### ISSUE TITLE
Where with IN (?) not re-binding parameters

### ISSUE THREAD

**Issue by hut8** [markbates/pop#123]
Hey there.

Nice ORM 😄 I'm having a bit of an issue with `.Where()` in which `some_column IN (?)` does not re-bind the parameters correctly.

First I translate my slice of strings to a slice of empty interfaces:

```go
	params := make([]interface{}, len(idList))
	for i := range idList {
		params[i] = idList[i]
	}
```

Then I run this:

```go
	err = DB.
		Where("some_id IN (?)", params...).
		All(&models)
```

 The error message produced is:

```
pq: got 21236 parameters but the statement requires 1
```

I see this: https://sourcegraph.com/github.com/markbates/pop@9e3f577a6ef58a6c412fb1cf6fae7a6e24689113/-/blob/sql_builder.go#L54:9 but I'm not sure if it's getting hit. I'll do more debugging later.

**Comment by markbates** [comment]
Try passing `params` instead of `params...`

**Comment by hut8** [comment]
` converting argument $1 type: unsupported type []interface {}, a slice of interface`

**Comment by markbates** [comment]
Sorry, my bad. I think it might be `in` not `IN`. Hard to debug, I'm on a phone. :)

**Comment by hut8** [comment]
```
re := regexp.MustCompile(`(?i)in\s*\(\s*\?\s*\)`)
```
The ?i makes it case insensitive, right? That's from your code in sql_builder.go 😄

**Comment by markbates** [comment]
I can't remember. If you use the lowercase in does it work?

**Comment by hut8** [comment]
It does not ☹️ Feel free to not debug this now 😄 You're the best open source maintainer ever. It's Friday night; I'll do some digging :)

**Comment by hut8** [comment]
Looks like it works perfectly with just:

```
DB.Where("some_column IN (?)", params...)
```

...however...

```
DB.Where("column_2 > ? AND some_column IN (?)", params...)
```

gives this error: `number of bindVars exceeds arguments` (returned from https://github.com/jmoiron/sqlx/blob/master/bind.go#L149)

I see why this happens; it's somewhat ambiguous (especially if you had multiple `IN(?)` predicates in the `WHERE` clause.

I think it  might be an improvement to not ignore this error here: https://sourcegraph.com/github.com/markbates/pop@9e3f577a6ef58a6c412fb1cf6fae7a6e24689113/-/blob/sql_builder.go#L57-58 since that was the only way I was able to track this down. Seems like more of a limitation of sqlx.

**Comment by hut8** [comment]
Related: https://github.com/jmoiron/sqlx/issues/338

**Comment by markbates** [comment]
Ah. Ok. The code example you sent was just the one clause. If you had sent me one that had two clauses I would've known exactly what the problem was. The workaround is to chain two clauses together. Where().Where()

If you have a suggestion on how to improve that error, I would love a PR for it.

-----------
Mark Bates

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
