### ISSUE TITLE
Bug in postgres prepared statement placeholders handling

### ISSUE THREAD

**Issue by josephbuchma** [markbates/pop#124]
Schema:
```
create_table("users", func(t) {
        t.Column("id", "integer", {"primary": true})
        t.Column("username", "string", {"size": 30})
        t.Index("username", {"unique": true})
})
```
Code
```go
db.Where("username=$1 OR id=$1", idOrUsername).First(&user)
```
Expected result: it fetches user and initializes `user` object if `id` or `username` matches.
Actual behavior: it does not initialize `user`.

Possible cause - types of username and id are different.
Similar code works when types are the same.

**Comment by markbates** [comment]
You need to use `?` and not `$1`. You also need to pass a value for each `?`.

-----------
Mark Bates

**Comment by josephbuchma** [comment]
Wow, that was fast response :)
Thanks! But in that case I'd like to be able to turn this placeholders processing off.
If you're not against such option, I may come up with PR.

**Comment by markbates** [comment]
I'm definitely not against the PR, though I wonder if it should be on the sqlx which is what handles the underlying statements.

-----------
Mark Bates

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
