### ISSUE TITLE
PostgreSQL SET on Query()

### ISSUE THREAD

**Issue by mkozjak** [markbates/pop#130]
Is there a way to use pg's SET while using `pop.Query` to set, ie., `search_path` to support querying across multiple database schemas with a single pg connection?

This would be nice in multi-tenancy system environments...

**Comment by markbates** [comment]
As far as I can think there isn’t, but PRs are welcome. :)

**Comment by mkozjak** [comment]
I feared those, haha. 😉

Gotta see how jmoiron/sqlx handles that...

**Comment by mkozjak** [comment]
I believe the only way is to use Query.RawQuery with SET LOCAL before the actual query so that only the current transaction is affected.

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
