### ISSUE TITLE
SQL migrations should have a suffix for the db dialect

### ISSUE THREAD

**Issue by stanislas-m** [markbates/pop#145]
Since the SQL syntax is not the same for each database, POP should have a way to choose the right patch to apply.

http://www.liquibase.org/ uses a suffix in the filename to get the right patch, like this: my_patch.mysql.sql & my_patch.postgresql.sql; it can be a way to implement that.

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
