### ISSUE TITLE
"<" is HTML encoded

### ISSUE THREAD

**Issue by dillonhafer** [markbates/pop#146]
I encountered this with buffalo, not sure if this is pop, fizz, or sqlx.

Given a migration:

```sql
create table years (
  id serial primary key,
  year integer not null check (year >= 2013 and year <= 2100)
);
```

The migration fails because `<` got turned into `&lt;` which prematurely terminates the sql statement.

```sql
Error: error executing migrations/001.up.sql, sql:
create table years (
  id serial primary key,
  year integer not null check (year >= 2013 and year &lt;= 2100)
);: pq: syntax error at or near ";"
```

**Comment by dillonhafer** [comment]
Oh dang, that was fast!

Thank you! ❤️❤️❤️

**Comment by markbates** [comment]
lol. you happen to catch me at my computer, and the change was so stupid simple. :)
