### ISSUE TITLE
empty `schema.sql` when migrating down

### ISSUE THREAD

**Issue by pjuanda** [markbates/pop#150]
I'm using `soda (v3.40.0)` in macOS High Sierra. I have no issue when migrating up, but when migrating down, it always create an empty file named `schema.sql` inside `migrations/` folder. Is this normal to be happened ?

**Comment by konradreiche** [comment]
What database do you use? This is likely due to missing database tools like `pg_dump` in the case of PostgreSQL.

**Comment by pjuanda** [comment]
hi @konradreiche, i am using PostgreSQL database and i've checked that my `pg_dump` is available and yet it still generate empty `schema.sql`.

**Comment by pjuanda** [comment]
eh, my bad. Yes, cause of the empty `schema.sql` is `pg_dump` in my case. After ensure `pg_dump` command availability, the `schema.sql` is not empty anymore. thanks @konradreiche
