### ISSUE TITLE
Fail to parse <> comparison operator in SQL migration

### ISSUE THREAD

**Issue by konradreiche** [markbates/pop#151]
SQL migrations containing the `<>` PostgreSQL operator seem to fail:

```
ALTER TABLE user ADD CONSTRAINT user_username_check CHECK (username <> '');
```

```
soda migrate up
> ALTER TABLE user ADD CONSTRAINT user_username_check CHECK (username &lt;> '');
```
This might be due to the template parser [here](https://github.com/markbates/pop/blob/master/file_migrator.go#L93).

**Comment by markbates** [comment]
This was fixed just recently. Please ensure you’re using the latest version, 3.40.0. If you are using the latest version, and this is still an issue, please re-open.
