### ISSUE TITLE
Whats the correct type to map money.

### ISSUE THREAD

**Issue by diegomgarcia** [markbates/pop#156]
Hi guys I`m new to go and pop, can you guys recomend whats the best way to work with money using pop with postgres ?

**Comment by markbates** [comment]
It's really a personal preference. A quick google of "how to store money in a database" will bring up a lot of results. The general consensus is to never use floats. I usually store money as an `int` (cents - $1.00 would be `100`). Others use different types, but I find `int` typically works well.

I have been playing around with using a string to store the amount and the currency here: https://github.com/markbates/cash it's still experimental though, so just be aware. :)
