### ISSUE TITLE
Step doesn't work if you provide a number other than 1

### ISSUE THREAD

**Issue by corylanou** [markbates/pop#159]
It appears that providing a number other than `1` to the migrate step command does not work.  It just does a single step every time.

```sh
$ buffalo db migrate down step 2
v3.40.1

< create_authors

0.0097 seconds
dumped schema for learn_development
```

I have a number of migrations and have tested each step that it works, but trying to do more than one step at a time fails.

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
