### ISSUE TITLE
sorting select columns, why?

### ISSUE THREAD

**Issue by u007** [markbates/pop#160]
hi ,

what is the reason to sort columns?
there are cases where we uses select distinct on (col1, col2) table.*, tableB.col1 from table...
where by the distinct on has to be the first column.
having it sorted will cause query error

```
func (c ReadableColumns) SelectString() string {
	xs := []string{}
	for _, t := range c.Cols {
		xs = append(xs, t.SelectSQL)
	}
	sort.Strings(xs) // why?
	return strings.Join(xs, ", ")
}
```

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
