### ISSUE TITLE
”DEFAULT COLLATE" of the Mysql database is fixed to "utf8".Utf8 string that uses 4 characters can not be used.

### ISSUE THREAD

**Issue by Yuutakasan** [markbates/pop#161]
change the default character to utf8mb4.

query := fmt.Sprintf("CREATE DATABASE `%s` DEFAULT COLLATE `utf8_general_ci`", deets.Database)
↓
query := fmt.Sprintf("CREATE DATABASE `%s` DEFAULT COLLATE `utf8mb4_general_ci`", deets.Database)

https://github.com/markbates/pop/blob/f244edc2b8f1335857465ccc9ede287aad6cd753/mysql.go

For reference, when Mysql 8 is released, I would like to use utf8mb4_ja_0900_as_cs.

Reference
http://mysqlserverteam.com/new-collations-in-mysql-8-0-0/
http://mysqlserverteam.com/sushi-beer-an-introduction-of-utf8-support-in-mysql-8-0/
http://mysqlserverteam.com/mysql-8-0-collations-the-devil-is-in-the-details/
http://mysqlserverteam.com/mysql-8-0-1-accent-and-case-sensitive-collations-for-utf8mb4/

**Comment by markbates** [comment]
A PR for this would be great.

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
