### ISSUE TITLE
exec function does not throw errors if grift fail or does not exists

### ISSUE THREAD

**Issue by u007** [markbates/pop#162]
hi,
is there update on this?
i also realize that environment variables is not passed into exec function.

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
