### ISSUE TITLE
PROPOSAL: Move markbates/pop to gobuffalo/pop and turn off SQLite support by default

### ISSUE THREAD

**Issue by markbates** [markbates/pop#164]

**Comment by markbates** [comment]
This proposal encompasses two major changes to Pop that, I believe, need/should happen at the same time.


## Part One: The Move

Pop has become an integral part of the Buffalo eco-system. Because of this, I believe the Pop repo should be moved from `markbates/pop` to `gobuffalo/pop`. This will help keep things closer in the eco-system, and, hopefully, make it easier for people to find, and contribute, to Pop.

My plan for moving the repo is, after the first of the year, to put `markbates/pop` into read-only mode and fork the repo to `gobuffalo/pop`. This will coincide with the start of the Buffalo version, `0.11.0`.

By putting `markbates/pop` into read-only mode, and updating the README to reflect the changes, we can keep existing applications running until they have time to move over to the new repo.

The `markbates/pop` repo will *not* get new features, bug fixes, etc...

## Part Two: SQLite

While it is great that Pop supports SQLite, its dependency on CGO has caused numerous problems over the years, especially since everyone has to have a GCC installed just to install Buffalo/Pop regardless of whether or not they plan to use SQLite.

To fix, I propose that after the repo is moved we flip support SQLite so that it is off by default, but can. be turned on using build tags.

The upside of this is that a GCC is no longer required to use Pop, but SQLite support is still in the support.

The downside is that in order to use SQLite users will need to rebuild the `buffalo/soda` binaries with the correct build tags to include SQLite support.

--

Currently this is my plan of action. I'm opening this up to the community for discussion, including potential pitfalls of this plan I have over looked.

Please leave your comments and lets discuss as a community.

**Comment by stuartellis** [comment]
+1 from me.

I experimented with Buffalo on Windows a while back, and SQLite was a surprising problem because of the GCC dependency. I worked around this by using a 3rd-party tool called scoop to handle the dependencies:

http://www.stuartellis.name/articles/buffalo-windows-short/

IMO, SQLite is only really useful here for bootstrapping a development environment for learners: professional developers should be using the same brand of database as is on their servers.

**Comment by arschles** [comment]
+1 from me as well.

FWIW I do happen to use sqlite for unit testing (I use postgres -- the same as production -- for integration testing), so I would still opt-in via the build flag, which is totally cool with me.

If I could propose one change to the soda CLI, it would be to publish cross-compiled binaries to the GH releases, including ones built with the sqlite flag turned on. As far as I know, the way to get the `soda` binary is to `go get` it. Assuming I'm not wrong, I think there's a usability problem for folks figuring out how to turn on a build tag when they `go get`.

I know the build matrix would be big, but I'm inclined to think that it would head off questions from folks along the lines of "how do I turn on SQLite support in soda??" if `go get` was the standard installation method.

I'm happy to PR this if folks think it's an ok way to go.

**Comment by markbates** [comment]
I would love to see pre-built binaries! A PR would be fantastic.

**Comment by arschles** [comment]
In progress in #172
