### ISSUE TITLE
Expose full sqlx connection?

### ISSUE THREAD

**Issue by mbetel** [markbates/pop#168]
Currently only a limited number of sqlx messages are available via Connection.Store. Could we also expose the raw *sqlx.DB in the Connection, then my legacy sqlx code using QueryRowx etc. can run off the same connection as Pop's. eg: 
```
type Connection struct {
	ID      string
	Store   store
	Dialect dialect
	Elapsed int64
	TX      *tX
	RawDB  *sqlx.DB
}

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
