### ISSUE TITLE
Add "upsert" functionality?

### ISSUE THREAD

**Issue by afstanton** [markbates/pop#170]
It would be very useful to be able to have this generate SQL for upserts. Conflict resolution might be tricky, though.

**Comment by markbates** [comment]
That sounds like a great idea. I would love to see a PR for it. The conflict resolution might be to allow for an optional function that let's the user decide the resolution. if they don't supply one, maybe just use the latest, or something like that.

**Comment by afstanton** [comment]
Yup, my thoughts exactly.

We use upsert a fair amount, so I will probably work on it in our fork and then if I get something useful I'll create a PR.

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
