### ISSUE TITLE
PROPOSAL: Preloading associations for a model

### ISSUE THREAD

**Issue by larrymjordan** [markbates/pop#189]
Hi @markbates , I opened this issue to discuss posible addition of automatic preloading association to pop package. I find a need to use this when in a project there is a model defined and  it needs to load not only its basic fields but also all its dependencies. I was guessing if it could be posible to do it without using **BelongsTo** and **BelongsThrough** functions and have all dependencies automatically loaded when finding.

Here I describe some approach  based on what already exist in this package with some additions, hoping can serve as a guide to achieve this.

The approach will be described in two parts:

- Defining preloadable fields in a model.
- Loading Preloadable fields associated to a model.

### Defining Preloadable fields in a model.
 
From package’s client perspective preloadable fields would be defined as a “db” field Tag with value “preloadable":

```go
 type User struct {
	Name               `db:"name"`
	Books        Books `db:"preloadable"` // => this can also be defined as a pointer i.e Books *Books
        FavoriteSong Song  `db:"preloadable"` // => this can also be defined as a pointer i.e FavoriteSong *Song
 }
```

From pop package perspective,  `github.com/markbates/pop/columns/Column` model will define a new field called `Preloadable` of type `bool` to indicate if a field is preloadable or not. (**Preloadable** is the name I chose so it can be cohesive with `Writable` and `Readable` fields already defined in this model)

```go
package columns

type Column struct {
      … 
      Preloadable bool
}
```

Later, when inspecting all fields tags for a model using `ColumnsForStructWithAlias` defined in `github.com/markbates/pop/columns/columns_for_struct.go` file, we can check and initialize all preloads fields defined in model.

```go
func ColumnsForStructWithAlias(s interface{}, tableName string, tableAlias string) (columns Columns) {
    ...
     st := reflect.TypeOf(s)
    ...
    
    fieldCount := st.NumField()

    for i := 0; i < fieldCount; i++ {
        field := st.Field(i)
        tag := field.Tag.Get("db")
        if tag == "" {
            tag = field.Name
        }

        ...

        if tag == "preloadable" {
            cs := columns.Add(field.Name)
            c := cs[0]
            c.SetPreload()
        }
        ...
    }
   ...
}
 ```

Here `c.SetPreload()` function setups some constraint for a preloadable column:

```go
  func (c *Column) SetPreload() {
       c.Preloadable = true
       c.Writable = false // column will not be selected when updating.
       c.Readable = false // column will not be selected when querying.
  }
``` 

### Loading Preloadable fields associated to a model.
From package’s client perspective, there will exist functions alike to `Find` and `All` called `FindAndPreload()` and `AllAndPreload()`  defined in `Connection` and `Query` types, so it can still be posible to support default loading from database.

```go
   // Find user with his/her books and his/her favourite song.
   u := User{}
   DB.FindAndPreload(&u, 1)
```

From pop package perspective, `FindAndPreload()` and `AllAndPreload()` will reuse `Find()` and `All()` existing functions to load all preloadable fields:

```go
   func (q *Query) FindAndPreload(model interface{}, id interface{}) error {
        // Reuse Find for query.
         err := err := q.Find(model, id)
    	if err != nil {
        	return err
	}
        

        // Get all preload columns defined for the model.
        m := &Model{Value: model}
       cols := columns.ColumnsForStructWithAlias(model, m.TableName(), m.As).Preload()
       
       // Iterate over every preloadable column and fill model field associated.
       for _, name := range cols {
           //1. get model field with name using reflection.
           //2. validate type of field.
           //3.1 call All() function with a reference of the model field as param if model field type is array or slice.
           //3.2 call Find() function with a reference of the model field as param if model field type is struct.
           //4. continue iterating.
       }

       return err
  }
```

This implementation of `FindAndPreload` and `AllAndPreload` works only to one level of dependency for a model, it means that is not recursive in case that a model dependency field has also preloadable fields defined. Also, it is taking into account only one to many, and one to one relationships. 
Hope I can receive some feedback and help to give form to this. Thanks.

**Comment by markbates** [comment]
I love this proposal. Thank you for the time you put into it!

Here are my couple ideas on the subject, in no particular order:

--- 

Instead of adding variations like `FindAndPreload`, what if we have something like an `Eager` function, that by defaults loads all the associations on the model, but can take a variadic list of associations to load.

```go
db.Eager().Find(model, 1)
db.Eager("Books").Find(model, 1)
```

---

I'm not crazy about the `preloadable` tag _name_, but that's just an implementation detail. We do need a way to describe what the foreign key is. By default we can figure out that, in this example, that it's `user_id`, but what if someone has a different key?

---

Those are my couple thoughts on it. What do you think?

**Comment by larrymjordan** [comment]
@markbates really like the `Eager()` function idea looks pretty nice, thanks. 

When defining an association, package's clients can use same `db` field tag with value equal to table name. This helps to define which fields are candidates to be associations based on the tag and type making easy implement `Eager()` function. 

```go
  type User struct {
      Books Books `db:"books"
  }
```

When scanning `User` we can expect `Books` field is an association because has a `db` tag defined and because is one of any of these kinds: **Ptr**, **Slice**, **Array**, **Struct**.  Then we can treat these fields as "specials columns" and use them in the `Eager()` function. 

About your question for a different key, you are correct, that implementation does not support it, I think we can handle it by defining a special tag. I don't have any idea for a name right now but...

```go
  type User struct {
     Books Books `db:"books" associated_to:"u_id"`
  } 
````

Let me know what do you think.

**Comment by markbates** [comment]
You can’t ignore struct types. It’s quite common to write custom types and implement the interfaces to serialize them. It has be a struct tag. 

I’m thinking tags like:
belongs_to:user
has_many:songs
fk_id:u_id

Thoughts?

**Comment by larrymjordan** [comment]
Those tag names are self explanatory, really good.  I have a question, how would you use the values for `belongs_to` and `has_many`?

**Comment by markbates** [comment]
Sorry, I wasn't near a computer last night when I typed that. Perhaps a bit of code would help:

```go
type User struct {
	ID        uuid.UUID `db:"id"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
	Books     Books     `has_many:"books"`  // looks for rows matching user_id in books table
	Address   Address   `has_one:"address"` // looks for 1 row matching user_id in addresses table
}

type Book struct {
	ID        uuid.UUID `db:"id"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
	UserID    uuid.UUID `db:"user_id"`
	User      User      `belongs_to:"user"`                                     // looks for a row in the users table
	Reviews   Reviews   `has_many:"publication_reviews" fk_id:"publication_id"` // looks for rows matching publication_id in publication_reviews table
}
```

If there's a `has_many`, `belongs_to`, or `has_one` tag, pop shouldn't load anything, it's like having `db:"-"`. 

However, if I were to do something like:

```go
db.Eager().First(&user)
```

It should load `Books` and `Address`.

If I did:

```go
db.Eager("Books").First(&user)
```

It would only load the `Books` association.

Does that help?

**Comment by larrymjordan** [comment]
@markbates yes. This looks nice.

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
