### ISSUE TITLE
belongs_to is restricted to one instance per target table 

### ISSUE THREAD

**Issue by macrael** [markbates/pop#199]
Been playing with the associations, I have a suggestion for re-working belongs_to to match rails better. If we have time early next week we will work up a PR with your blessing.

In short: right now belongs_to looks for an ID field called `field.type + id` but I think it would be better for it to be `field.name + id`. This would allow you to have multiple belongs_to to the same table, and matches rails style. 

type Order struct {
    ItemName string
    ShippingAddressID uuid.UUID `db:"shipping_address_id"`
    ShippingAddress Address `belongs_to:"address"`
    BillingAddressID *uuid.UUID `db:"shipping_address_id"`
    BillingAddress *Address `belongs_to:"address"`
}

We also have run into a bug I think is related to using pointers for nullability so we'll look into that too.

**Comment by markbates** [comment]
I agree it should be field_name_id by default. But I don’t think it’s restricted. You can use the fk_id to change the name of the column you’re looking for, so that’s a “workaround”.

**Comment by macrael** [comment]
I don’t believe that applies to belongs to, just has one. But I may have misread. 

—MacRae

**Comment by markbates** [comment]
cc @larrymjordan

**Comment by larrymjordan** [comment]
@markbates @macrael thanks for giving an inspection and exploring this feature, means a lot. What you propose for `field_name_id` seems reasonable and based on your example makes sense. Now, regarding to the `BillingAddressID *uuid.UUID`  field, the `belongs_to` association right now does not support pointers for the `foreign key` and that causes the bug you mentioned before.  @markbates I don't see any problem with a PR, that would be very helpful.

**Comment by markbates** [comment]
I agree. I think PRs for this stuff would be very helpful!

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
