### ISSUE TITLE
Provide examples

### ISSUE THREAD

**Issue by neutronstein** [markbates/pop#20]
Providing some examples(clear and concise) would help getting started quickly.
Thanks

**Comment by grimmy** [comment]
Seconded, I'm getting null pointer deferences and haven't figured out whats going on yet...

**Comment by mixedCase** [comment]
I'm still not sure wether I'm supposed to start a new Connection on every query or if it behaves like database/sql and sqlx where the DB struct represents a connection pool.

Docs are definitely needed.

**Comment by markbates** [comment]
PRs for docs are definitely welcome. To answer your question, pop, uses sqlx under the cover, which in turns wraps the sql package. So, connection pooling is automatically implemented for you.

**Comment by mixedCase** [comment]
@markbates And what about transactions? Looking at the transaction code, if I share the same *pop.Connection it seems that if I open a transaction in a goroutine while another is still not done with its own, it will try to use the latter's; unlike sqlx where transactions are separated.

In other words, with sqlx I can safely share *sqlx.DB between all my goroutines and can freely call its methods without explicitly opening and closing connections. What's the equivalent for this in pop?

**Comment by markbates** [comment]
Transactions on a po.connection are not shared. You get a new transaction. However if you try to create a transaction on a transaction you get back the original transaction.

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
