### ISSUE TITLE
[error] Does not have privilege

### ISSUE THREAD

**Issue by danikarik** [markbates/pop#200]
Hi!

I published [coke-demo](https://github.com/danikarik/coke-demo) to reproduce error. Project uses Buffalo. Run `buffalo test`:

```
dropped database coke_test
created database coke_test
Usage:
  buffalo test [flags]

Flags:
  -h, --help   help for test

ERRO[0000] Error: pq: user maxroach does not have CREATE privilege on database coke_test
Error: pq: user maxroach does not have CREATE privilege on database coke_test
Failed running "sql"
: exit status 1
```

**Comment by markbates** [comment]
According to the error message your user doesn’t have sufficient privileges to create the database. Make sure to give your user the correct privileges and you should be good.

**Comment by danikarik** [comment]
I grant all privilege on database to user. When I run test, it drops database first with all existing grants, and then creates new database. But problem is that grants are removed.

**Comment by markbates** [comment]
Don't grant privileges for a specific database. Grant them to PG globally. https://support.rackspace.com/how-to/postgresql-creating-and-dropping-roles/

**Comment by danikarik** [comment]
Can I do the same in Cockroach DB?

**Comment by markbates** [comment]
I don't know, I don't use Cockroach. @mclark4386 any ideas here?

**Comment by danikarik** [comment]
In my database config I use `root` as user. But error refers to maxroach user, because of this [line](https://github.com/markbates/pop/blob/master/cockroach.go#L202). Can this be a problem?

**Comment by markbates** [comment]
@danikarik I believe @mclark4386 fixed this a few minutes ago. Here's the release https://github.com/markbates/pop/releases/tag/3.60.1

**Comment by danikarik** [comment]
@markbates @mclark4386 You did mistake in [line](https://github.com/markbates/pop/blob/master/cockroach.go#L202).

Cmd run command: `cockroach sql --insecure --database "testdb --user=<user>"`. And gets error like: `Error: pq: database "testdb --user=root" does not exist`

It should be:
`cmd := exec.Command("cockroach", "sql", secure, fmt.Sprintf("--database=%s", p.Details().Database), fmt.Sprintf("--user=%s", p.Details().User)))`

**Comment by mclark4386** [comment]
@danikarik good catch! Sorry about that! I thought I was saving cycles, but didn't realize exec.Command would add "s like that. PR with fix is in and hopefully @markbates or someone else can merge it in the morning!
