### ISSUE TITLE
[error] Cockroach DB tests return "missing destination name table_name in *[]pop.table"

### ISSUE THREAD

**Issue by danikarik** [markbates/pop#206]
Hi!

I was running tests for cockroach db and got error on `TruncateAll` method:

```
level=debug msg="select table_name from information_schema.tables;"
--- FAIL: Test_ActionSuite (0.02s)
    --- FAIL: Test_ActionSuite/Test_Auth_Login (0.01s)
        Error Trace:    model.go:20
    	            	suite.go:47
    	            	suite.go:88
    	Error:      	Received unexpected error:
    	            	missing destination name table_name in *[]pop.table
    	            	github.com/danikarik/coke-demo/vendor/github.com/markbates/pop.genericSelectMany
...
```

To reproduce error you can clone this [repo](https://github.com/danikarik/coke-demo).

Steps:
1) install buffalo with `go get -u -v github.com/gobuffalo/buffalo/buffalo`
2) run `dep ensure`
3) execute `buffalo test`

**Comment by markbates** [comment]
@mclark4386 would you mind taking a look at this?

**Comment by mclark4386** [comment]
@markbates will take a look

**Comment by mclark4386** [comment]
@markbates That PR should fix it^^
