### ISSUE TITLE
Possible to run fileMigrator.Up() without dump?

### ISSUE THREAD

**Issue by miguelmota** [markbates/pop#210]
Hi, is it possible to run the file migrator without dumping the entire schema? currently when I run `fileMigrator.Up()` it outputs the schema to `migrations/schema.sql` which takes a really long time

code I'm using

```go
	db, err := pop.Connect("development")
	if err != nil {
		log.Panic(err)
	}
	fm, err := pop.NewFileMigrator("./migrations", db)
	if err != nil {
		log.Panic(err)
	}
	err = fm.Up()
	if err != nil {
		log.Panic(err)
	}
```

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
