### ISSUE TITLE
web server hang after meeting connection pool limit

### ISSUE THREAD

**Issue by u007** [markbates/pop#211]
hi,

i'am not sure if this is buffalo or pop related problem.
when i have connection pool set to 5, 
and i run apache bench
```
 ab -n 20 -c 6 http://127.0.0.1:3005/api/something
```
my web server hang.

even after waiting for minutes, and calling the url via curl, it still hang

any idea how we can fix this?
i know its possible to remove connection pool,
but im worried that it might grows over board.
there are options to set db.SetMaxIdleConns(maxIdle)
but how do we set this in database.yml?

thank you

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
