### ISSUE TITLE
Proposal: Allow pop import without valid database.yml file

### ISSUE THREAD

**Issue by rweald** [markbates/pop#25]
Just an idea I had that could make certain testing/dev cases easier. Right now if there is a dialect parse problem with any of the environments in your database.yml file regardless of whether it is used a fatal log causes the program to crash. It might be nice if as a user you could more explicitly handle this error. 

An alternative to actual code changes could simply be some additional documentation that makes the need for valid dialects in all database.yml environments more explicit. 

I am happy to help with the patch/docs if you think this is a valid addition. Thank you for your time

**Comment by markbates** [comment]
I would love to see a PR or a proposal for this.

**Comment by XelaRellum** [comment]
I think the PR I created a few minutes ago addresses this. I stumbled over this problem in a project that doesn't use POP at all because it is bound to some legacy database (creating a dialect for POP is not viable for now). But since I work with Buffalo which in turns uses pop... BAM. Just wanted to run "buffalo dev" but got the panic instead...

**Comment by rweald** [comment]
Awesome. I had been battling with how to make it in a backwards compatible way.

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
