### ISSUE TITLE
Use build tags to exclude unneeded database support

### ISSUE THREAD

**Issue by stanislas-m** [markbates/pop#27]
Most of the time, I will work with a single type of database for a given project. Go build tags can be used to exclude source for unneeded database support (as well as their dependencies).

For instance:

Add a build flag at the top of `mysql.go`
``` go
// +build !exclude_mysql
```

Add a new `without_mysql.go` file to handle compilation problems:

``` go
// +build exclude_mysql

package pop

func newMySQL(deets *ConnectionDetails) dialect {
	panic("MySQL support disabled")
}
```

Build (or install) pop without mysql support (-x flag just for verbose):
``` bash
go build -tags 'exclude_mysql' -x
```

**Comment by markbates** [comment]
I would love to see a PR for this, but instead of `exclude` I would like to see the other way around, where a build tag is used to include. 

I would also like to see how this would work with the `soda` binary and https://github.com/gobuffalo/buffalo

**Comment by stanislas-m** [comment]
Sure. I'll try to find some time soon. :)

**Comment by markbates** [comment]
sweet!

**Comment by stanislas-m** [comment]
@markbates I've pushed the feature here https://github.com/stanislas-m/pop/commit/250f6c1de6beaabb2cea4980439ec204e90ae3cb

It can be used like this:
`go build -tags 'mysql_driver'`

or even like this, to support multiple drivers:
`go build -tags 'mysql_driver sqlite_driver'`

You can use -x flag to check which files are compiled (without_* files or normal ones).

The implemented behavior is to panic if a non-compiled driver is used. This can cause problems when unused config is declared in database.yml, so I don't know what behavior to use here (skipping the connection with a warning? Failing with a user-friendly message?). I'll have to fix the Dockerfile anyway.

For buffalo case, I think we can use the `dbType` arg to build the needed version.

**Comment by mkozjak** [comment]
Any progress on this one? I only use postgres and I still got 
```
github.com/qaap/crowd/vendor/github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in $PATH
```
in Docker even though there's no sqlite3 settings in database.yml...

**Comment by markbates** [comment]
You can use the the build tag `nosqlite` to turn off SQLite.

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
