### ISSUE TITLE
Make Connection (and possibly Query) into interface types

### ISSUE THREAD

**Issue by bigblind** [markbates/pop#31]
This would allow passing stubs, spies and other test doubles to functions that normally take a connection, in order to avoid database access in unit tests.

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
