### ISSUE TITLE
Add MariaDB support

### ISSUE THREAD

**Issue by stanislas-m** [markbates/pop#34]
As MariaDB is a "drop-in" replacement for MySQL, I don't think it will be difficult to add support for it.

**Comment by markbates** [comment]
I've never used MariaDB, I'm a Postgres guy myself. :) What would be needed to add support for it, or would the MySQL adapter work just fine?

**Comment by stanislas-m** [comment]
According to https://mariadb.com/resources/blog/using-go-mariadb, the MySQL adapter will work fine. :)
So, maybe we can just add mariadb as a synonym dialect for mysql.

**Comment by hubyhuby** [comment]
Great idea, I am a mysql guy :) 
Actually I installed mariadb and I was assuming  that it would be working with pop as it had a mysql connector...
Can confirm I didn t get it to work with mariadb and 0.10.x

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
