### ISSUE TITLE
Can you support for mssql?

### ISSUE THREAD

**Issue by kumarsiva07** [markbates/pop#35]
Mssql driver is already [there](https://github.com/denisenkom/go-mssqldb). Is it possible to add dialects?

**Comment by markbates** [comment]
There currently isn't support for MsSQL. I would welcome the addition of it via a PR.

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
