### ISSUE TITLE
Generated model with a name beginning with "b" fails to compile

### ISSUE THREAD

**Issue by stanislas-m** [markbates/pop#38]
https://github.com/markbates/pop/blob/master/soda/cmd/generate/model_templates.go#L17 and https://github.com/markbates/pop/blob/master/soda/cmd/generate/model_templates.go#L26 will fail if the model starts with "b".

See https://github.com/gobuffalo/buffalo/issues/261

**Comment by markbates** [comment]
Sounds like an easy PR for someone. :)

**Comment by markbates** [comment]
Closed via https://github.com/markbates/pop/pull/39
