### ISSUE TITLE
Proposal: Pop v4

### ISSUE THREAD

**Issue by markbates** [markbates/pop#43]
The Pop v3.x.x range is starting to show its age, and its limitations. It's time to start thinking about the next major revision of Pop. This document is a meant to be fairly broad in scope, something to start tacking ideas on to and figuring out what v4 should look like.

At first glance I don't see much changing in the `soda` command or the `fizz` functionality. However, their generators will most likely have to change to work with whatever v4 ends up being.

- Relationships. Being about to access a has many or a belongs to relationship on a model would be really nice. This seems to be the most requested featured. This is a tricky feature. Most people want to be able to do something like `user.Widgets` and get all the widgets for the user. The problem with this sort of "on demand" loading is that the connection to the database is required, so real thought is going to be needed to figure out the best way to do this.
- User definable primary keys. Right now Pop supports either `int` or `uuid.UUID` primary keys, it would be great to allow for user defined primary keys.
- Reduce the amount of "magic" currently in the code. While Pop definitely uses less magic than most, there is still plenty in there that makes things a bit hairy at times. Investigate ways to clean some of that up.
- Investigate using relation algebra to build queries, similar to what ActiveRecord does with Arel. Whether that's necessary or not, I'm still unsure of.
- Reduce duplication between `pop.Connection` and `pop.Query`.
- Use more, and smaller, interfaces to make mocking easier.
- Use Go plugins (would require minimum version of `1.9`) to split out dialects so only those that people want will be loaded. If Go plugins don't work on all platforms in 1.9, than a different approach will need to be implemented.

Please feel free and comment on this issue with feature ideas, improvements, suggestions on how the API should look, etc...

There is currently no timeline for this release, or the start of development. I want to make sure we have a good solid understanding of how it should work, and what it should all look like, before development starts.

**Comment by bigblind** [comment]
For the case where a field maps to a single value, like a one-to-one mapping, or one-to-many, in the directiion of the one model, you could do:

`pop.Q(con).WithRelated("User").All(&widgets)`

Assuming `Widget` has a struct field named `User` that stores a user model.

Not sure how to handle the `-many` side of relationships though. You'd want the flexibility of other queries as well.

**Comment by markbates** [comment]
This suggestion comes from @webRat:

He would like to be able deference a row into a struct that contains other structs.

Example:

```sql
select u.*, a.* from users as u, addresses as a where a.user_id = u.id 
```

```go
type Address struct {
  PostalCode string
}

type User struct {
  Name string
  Address Address
}

**Comment by u007** [comment]
would be nice if there are option to run seed.
and any ways to generate schema so that we can run load schema?

**Comment by markbates** [comment]
I have a branch right now where I'm working on load and dumping of schemas.

**Comment by Michsior14** [comment]
I would love to see preloading with joins instead of selects :) 
Btw. @markbates Is nested scans (bind to struct) currently supported?

**Comment by u007** [comment]
maybe something like
```
pop.Q(tx).FetchChild(&user, "Address") 
```

**Comment by u007** [comment]
Also, it would be great if Query now accept Selected fields.
Because of the current restriction of fields to be last method to call,
people sometimes beed to duplicate codes for different condition when they need to have more "Where" condition later with the same selected fields

**Comment by nyrf** [comment]
Any update? Is there a way to get relationship records now?

**Comment by sdcoffey** [comment]
Huge ➕ for plugin support. I'm a huge fan of this library, but I haven't figured out a way to avoid compiling sqlite when this project is vendored. It's a huge time sink.

**Comment by markbates** [comment]
Unfortunately go plugins aren’t being well maintained by the Go team and still only support Linux. You can build with the `nosqlite` build tag to avoid SQLite if you’re not using it.
