### ISSUE TITLE
Panic running soda config

### ISSUE THREAD

**Issue by fooflare** [markbates/pop#44]
```
:~$ soda g config

panic: [POP]: Tried to load configuration file, but couldn't find it.

goroutine 1 [running]:
github.com/markbates/pop/soda/cmd.init.9()
	/home/fooflare/.go/src/github.com/markbates/pop/soda/cmd/root.go:50 +0x247
github.com/markbates/pop/soda/cmd.init()
	/home/fooflare/.go/src/github.com/markbates/pop/soda/cmd/version.go:4 +0x93
main.init()
	/home/fooflare/.go/src/github.com/markbates/pop/soda/main.go:8 +0x44
```

This issue is crashing Buffalo: https://github.com/gobuffalo/buffalo/issues/266

**Comment by fooflare** [comment]
The code that is generating this issue is:

from: https://github.com/markbates/pop/blob/master/soda/cmd/root.go#L47
to: https://github.com/markbates/pop/blob/master/soda/cmd/root.go#51

Now I have 2 questions:
  1. Has any sense to load configuration here when is being done in PersistentPreRun?
  2. Has any sense to load configuration if database.yml doesn't exist?

I am a bit confused with this code. Before the last PR was not panicking because the value of pop.LoadContig() was not being saved in a variable, but the file didn't still exist due to being loaded before the command was executed. Am I wrong?

Sorry for so many questions :) and thanks

**Comment by markbates** [comment]
I've rolled back those commits, so this should be working now.

**Comment by fooflare** [comment]
ooops!!! My bad for not saying anything, I was working in a patch :(

**Comment by markbates** [comment]
No worries. I wasn't happy with that set of commits. I understand the problem it was solving, but might not have been the best approach.

**Comment by fooflare** [comment]
Ok, I was already configuring the tests so I will finish in my branch just for learning :) at least it was good to realize how pop works

**Comment by fooflare** [comment]
In case you change your mind and want to have a look, here is the branch of my fork:
https://github.com/fooflare/pop/tree/config
The only problem was with the configuration command.
