### ISSUE TITLE
show line number in fizz migration

### ISSUE THREAD

**Issue by u007** [markbates/pop#46]
hi,

is it possible to show line number of the executed migration that throws the error?
and also possibilities of the sql syntax that caused it?

ive encounter error:
```
error inside of calling function: pq: column "fieldname" contains null values.
```
and i found the fix was simply adding null: true, or default: ""
```
add_column("users", "fieldname", "string", {"size": 255, "null": true})
add_column("users", "fieldname", "string", {"size": 255, "default": ""})
```

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
