### ISSUE TITLE
migration down roll back all?

### ISSUE THREAD

**Issue by u007** [markbates/pop#47]
hi,

why is rollback running all backward migration?
normally in rails, migration up means running all, but down means only 1, unless specified all.

**Comment by markbates** [comment]
A PR for this would be great, and fairly easy.

**Comment by u007** [comment]
https://github.com/markbates/pop/pull/49

**Comment by u007** [comment]
hi,

when will this be made public?
how do i install the latest version and run it,
do i need to run go get -u github.com/markbates/pop?

thanks

**Comment by markbates** [comment]
This was merged about 10 days ago. You just need to get the latest version and you'll be all set.

**Comment by u007** [comment]
i have vendor directory locally on my machine.
does buffalo command runs using my vendor directory latest pop, 
or does it run from go path src directory?

thanks
