### ISSUE TITLE
transaction with destroy: error committing or rolling back transaction: sql: Transaction has already been committed or rolled back

### ISSUE THREAD

**Issue by u007** [markbates/pop#48]
i tried:
and received this:
error committing or rolling back transaction: sql: Transaction has already been committed or rolled back
is this the proper way to destroy a model?
```
err := tx.Transaction(func(tx *pop.Connection) error {
		err := tx.Dialect.Destroy(tx.Store, &user)
		if err != nil {
			c.Logger().Errorf("destroy error!")
		}
		return err
	})
```

**Comment by markbates** [comment]
https://godoc.org/github.com/markbates/pop#Connection.Destroy

Use the Destroy method on the connection or transaction.

-----------
Mark Bates

**Comment by u007** [comment]
ive tried this, same error...
```
err := tx.Transaction(func(tx *pop.Connection) error {
		err := user.Destroy(tx)
		if err != nil {
			c.Logger().Errorf("destroy error!")
		}
		return err
	})

func (u *User) Destroy(tx *pop.Connection) error {
	if u.IdIsNil() {
		return fmt.Errorf("Invalid user")
	}

	//any pre destroy here

	return tx.Destroy(u)
}
```

**Comment by u007** [comment]
how come for every query and update or delete or create, it creates  a transaction and commit / rollback?

**Comment by u007** [comment]
there must be a way for us to manually commit and rollback,
right now, since transaction takes back old connection, this is impossible to achieve

**Comment by markbates** [comment]
I'm sorry, I don't understand. Are you opening a transaction on a transaction? If so, that's the problem. you can't nest transactions. If you do that committing the inner most transaction will close the outer most transaction.

**Comment by markbates** [comment]
Most databases do not allow nested transactions.

**Comment by u007** [comment]
okay , i understand, but what if i need to run multiple update in 1 transaction?

**Comment by markbates** [comment]
You can run as many queries, updates, etc… as you want inside of a transaction. That's not a problem. 

You may want to consider using this middleware https://github.com/gobuffalo/buffalo/blob/master/middleware/pop_transaction.go it will wrap each HTTP request in a transaction and commit or roll it back for it. It will also log the time spent in the databas for it. It'll clean up a lot of that code for you.

**Comment by u007** [comment]
ohh, so it works if i call multiple tx.Find, and tx.Destroy(user) and both is wrapped in the transaction?

**Comment by markbates** [comment]
That looks like it should work.

**Comment by u007** [comment]
thank you :)
where does it display the db timing?

**Comment by markbates** [comment]
It displays it in the log as "db".

**Comment by u007** [comment]
Hi @markbates 

thank you so much for the help :)
great framework so far 👍 

im having a new issue,
i use tx to do validation and and use the same tx pop connection to check for existing record,
and then finally call tx.Create, it throws:
```
error inside of calling function: pq: current transaction is aborted, commands ignored until end of transaction block
```

**Comment by u007** [comment]
okay sorry my bad, i realize ive a wrong query that causes the tx to fail
