### ISSUE TITLE
Mysql create with int64 primary key

### ISSUE THREAD

**Issue by natedsaint** [markbates/pop#63]
I'm not 100% sure this is an error, but digging through the code, this is where I landed: 
https://github.com/markbates/pop/blob/b1d0aece697e3be3ea3aaeab884e00725e04f2b8/dialect.go#L40

This happens when I try to use a model that has an int64 as the ID field. Here's the error specifically: 
`2017/04/17 16:33:51 error inside of calling function: mysql create: can not use int64 as a primary key type!`

This happens when I attempt to do a db.Create(&model) where the model struct ID is int64.

Looking at the code, it seems as though it's expecting "int", but then it immediately converts that to an int64. The problem here is that I'm mapping auto-generated Swagger models (which by convention are using int64 IDs) to these fields. I can get around this by converting them back and forth but it seems to me that is a waste of resources. Maybe I'm missing something?

Here's the code example that's causing me grief: 
FROM swagger model: 
```
findErr := db.Find(campaign, int(params.ID))
```
FROM pop model:
```
payload := swaggerModels.ObjectResponse{
			Name:      popModel.Name,
			ID:        int64(popModel.ID),
		}
```

Any thoughts on this?

**Comment by markbates** [comment]
You can use either ints or uuids for a primary. The reason it's int and not int64 was to make it compatible across 32 and 64 bit systems. I would happily accept a PR add int64 support. There are only a couple of places you would have to tweak.

**Comment by natedsaint** [comment]
Sure, I'd be happy to look! Where I'm confused by that is in line 41 of the above, wouldn't that force 64-bit regardless of the intent going in? I'm new to golang, so I apologize if I'm missing something here with regard to where the compilation happens given external packages and so forth.

**Comment by markbates** [comment]
It would. I can't remember how that bit of code evolved to be honest. :)

**Comment by natedsaint** [comment]
Right on, I know how that goes =D

I'll fork this and take a look tomorrow, see where I can help out.
