### ISSUE TITLE
DB reverse tools 

### ISSUE THREAD

**Issue by ninja9158** [markbates/pop#64]
For an existing database, it is time-consuming to write all the models。
It would be great to be able to generate a structural definition in batches

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
