### ISSUE TITLE
Vendoring strategy for pop/sqlx

### ISSUE THREAD

**Issue by webRat** [markbates/pop#7]
Since pop is a wrapper for sqlx and pop doesn't vendor sqlx, what are your recommendation for keeping in sync with `x version` of sqlx?

**Comment by markbates** [comment]
That's the age old question in Go: "How does a library vendor/lock a dependency?". I don't have an answer, since it's a hotly debated topic through out the community. I had thought of vendoring, but a lot of people feel that a library shouldn't vendor, only an application. I'm open to suggestions.
