### ISSUE TITLE
If id field is provided to soda, default ID should not be generated

### ISSUE THREAD

**Issue by stanislas-m** [markbates/pop#73]
Using soda, I tried to generate a new model using the following command (buffalo integration):

```bash
$ buffalo soda g m forum_topic_type id:string
```

The generated model contains two ID columns, one as a UUID, the other as a string. When the id field is provided, the default ID column should not be generated. Maybe add some checks to ensure ID type is supported.

**Comment by sio4** [comment]
I also tried this. Although I like UUID as primary key, sometimes it is not possible. (for example using existing systems or integrate with them) please consider this.
