### ISSUE TITLE
User specific value for 'ID'

### ISSUE THREAD

**Issue by sio4** [markbates/pop#75]
Hello,
When I create an object from buffalo, and I assign specific value for ID (integer ID), it was not affect to DBMS. my environment is buffalo 0.8.2 with MySQL.

Does pop support user assigned value for ID? Because my program have copied tables from other service, the ID is already exist for each record. I also considered using another name of field for copied ID but it will make the program a lot complicated.

Is there any solution?

**Comment by sio4** [comment]
Hello, I found [this line](https://github.com/markbates/pop/blob/master/dialect.go#L42) but I could not find how can I set the `id` as writeable. please let me know.

**Comment by markbates** [comment]
Currently Pop manages ID creation, you can't set your own ID.
