### ISSUE TITLE
Soda config generator under windows creates wrong paths for sqlite dbs

### ISSUE THREAD

**Issue by as27** [markbates/pop#77]
Running `soda g config -t sqlite` under windows 10 generates wrong paths inside `database.yml`.
The path looks for example like this:
`/\src\test\coke/C:\Users\schroepfer\    go\src\test\coke_test.sqlite`

The issue is the "mix of slashes" here, because of the windos `\`

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
