### ISSUE TITLE
Roadmap or feature-complete?

### ISSUE THREAD

**Issue by mixedCase** [markbates/pop#8]
I was wondering if there was any roadmap for the project or if it's considered "done".

**Comment by markbates** [comment]
Hi @mixedCase there isn't any proper "roadmap" for `pop` or `soda`. Version 3.x is currently very stable (and being used in production), so there likely won't be any breaking features or changes in the near term.

I've sketched out ideas for a 4.x, but no timeline or anything really concrete yet.

There is definitely a need for more/better documentation, which I would certainly welcome PRs for. 

I hope that answers your question.

**Comment by mixedCase** [comment]
It does. Thanks for replying!
