### ISSUE TITLE
Soft Delete?

### ISSUE THREAD

**Issue by natedsaint** [markbates/pop#81]
Is there anything planned/supported similar to the `gorm` method of providing a `DeletedAt` field, which then makes destroys update that instead? If not, is this a feature anyone would use? I can look into a PR if so, but the trick will be filtering out the `Read` operations to filter out deleted stuff unless otherwise specified.

**Comment by timsayshey** [comment]
Hey @markbates - Are there any plans to support this in the future? What is the best way to deal with this in the meantime? Thanks!

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
