### ISSUE TITLE
How to use callbacks?

### ISSUE THREAD

**Issue by viktorbenei** [markbates/pop#83]
Is there any docs about this? I thought simply defining a `BeforeCreate` function for the model object should be enough, but it seems that's not called by `tx.ValidateAndCreate(worker)`.

```
// BeforeCreate ...
func (w *Worker) BeforeCreate(tx *pop.Connection) error {
	log.Println(" (debug) BeforeCreate ...")
	return nil
}
```

P.S.: Worker is a resource generated through `buffalo g resource` as well as `tx.ValidateAndCreate(worker)` is from the buffalo auto generated Create action.

**Comment by markbates** [comment]
Using the https://github.com/gobuffalo/toodo project, I see it working correctly.

```go
func (t *Todo) BeforeCreate(tx *pop.Connection) error {
	fmt.Println("I am in the BeforeCreate")
	return nil
}
```

```go
func (v TodosResource) Create(c buffalo.Context) error {
	t := &models.Todo{}
	err := c.Bind(t)
	if err != nil {
		return err
	}

	tx := c.Value("tx").(*pop.Connection)
	verrs, err := tx.ValidateAndCreate(t)
	if err != nil {
		return err
	}
	if verrs.HasAny() {
		c.Set("todo", t)
		c.Set("errors", verrs.Errors)
		return c.Render(422, r.HTML("todos/new.html"))
	}
	c.Flash().Add("success", "Todo was created successfully")
	return c.Redirect(301, "/todos")
}
```

```
I am in the BeforeCreate
[POP] 2017/06/24 21:42:28 INSERT INTO todos (completed, created_at, description, id, title, updated_at) VALUES (:completed, :created_at, :description, :id, :title, :updated_at)
time="2017-06-24T21:42:28-04:00" level=info content_type="application/x-www-form-urlencoded" db=1.031186ms duration=1.900824ms form="{"Description":[""],"Title":["asdfasdfasdf"]}" human_size="0 B" method=POST params="{}" path="/todos" request_id=0a6415aaa7-bc1bfe323f size=0 status=301 
```

The callbacks won't get called if there are any validation errors, perhaps that's why you're not seeing them.

**Comment by viktorbenei** [comment]
OK, mystery solved. The issue was that `Validate` is called **before** `BeforeCreate` is called, and `BeforeCreate` is supposed to generate an ID for this model which if missing will make `Validate` to fail.

Is there a callback option which would run **before** `Validate`? Specifically I only want to run this before the creation of the model, to auto generate a token for it.

**Comment by viktorbenei** [comment]
Thanks for the quick reply @markbates - I sent my comment exactly when you replied :P

**Comment by markbates** [comment]
You caught right as I was about to go to bed, so good timing. :)

I just looked and there aren't any callbacks before/after validation (someone else added callbacks, not me). It wouldn't be hard to add them, and I would definitely be open to a PR for it. 

A simple "workaround" would be to use one of the `Validate` methods to set it if it doesn't exist. `Validate` gets run on all executors. There's also `ValidateSave`, `ValidateUpdate`, and `ValidateCreate`.

**Comment by viktorbenei** [comment]
> There's also ValidateSave, ValidateUpdate, and ValidateCreate.

Indeed that's what I started to explore just right now, but it seems `ValidateCreate` runs **after** `Validate`?

**Comment by viktorbenei** [comment]
I ended up just adding a generator function to the model and calling it in the buffalo action / "controller", which I think makes sense in this specific case as the token I wanted to auto generate should only be auto generated if that specific endpoint is called.

I guess it's just my Rails background why I tried to go with a callback in the model :)

That said, I'm not sure why `ValidateCreate` is called after `Validate`. For me it seems strange to have a validator which is only called on create but after `Validate`. I might miss something but it feels wrong to have a validator which only runs in case of a create - I was expecting `ValidateCreate` to be a kind of "before validate" callback.

Is this intentional (that `ValidateCreate` is called after `Validate`)? Would it make sense to change the order at https://github.com/markbates/pop/blob/master/model.go#L79 ?

**Comment by markbates** [comment]
`Validate` always runs, for all actions. To me it makes sense to run that first before the event specific one.

**Comment by viktorbenei** [comment]
Makes sense, although I still think there would be a place for a before-validate method/callback especially for "create", just in case you have to auto generate a token or similar for the model. That could be useful I believe :)

**Comment by markbates** [comment]
Totally agree. Before validation callbacks would be great. I would love it if someone opened a PR with them. ;)
