### ISSUE TITLE
Option to initialize with an existing *sql.DB

### ISSUE THREAD

**Issue by viktorbenei** [markbates/pop#85]
Maybe I missed this option somehow, but I can't find a function to init a pop connection with a *sql.DB

In our case this would make the migration way easier, as right now we don't use pop for the main project but would consider to test and possibly migrate if it works out.

For that we'd need an option to use an existing `*sql.DB`, just like the `NewDb` function of sqlx (https://github.com/jmoiron/sqlx/blob/master/sqlx.go#L247).

Is there an option for this? If not, would you be open to add/accept a method like the sqlx `NewDb` one?

**Comment by viktorbenei** [comment]
I might have some time working on this - @markbates what do you think about this? Would you be against an "init Connection with `*sql(x).DB`" function?

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
