### ISSUE TITLE
Add migration type flag when creating a model

### ISSUE THREAD

**Issue by mkozjak** [markbates/pop#86]
We should be able to optionally choose whether we'd like to have migrations generated as sql files rather than fizz ones by default.

ie:
`soda g model user name:text password:text --migration-type sql`
`soda g model user name:text password:text -t sql`

Does that make any sense? Or should I use --skip-migration and use g sql instead?

**Comment by markbates** [comment]
I would definitely welcome a PR for this.

**Comment by mkozjak** [comment]
@markbates: Can you, please, check on #89

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
