### ISSUE TITLE
id entered multiple times with model generate

### ISSUE THREAD

**Issue by mkozjak** [markbates/pop#87]
In example, if we do
`generate model subscriber id:int uid:text name:text status:boolean ddd:timestamp`,
we'll end up with both
`t.Column("id", "uuid", {"primary": true})`
and
`t.Column("id", "integer", {"primary": true})`
in our migration file.

**Comment by markbates** [comment]
Well, that shouldn't happen. :) A PR to fix this would be very welcome.

**Comment by stanislas-m** [comment]
Related to #73.

**Comment by stanislas-m** [comment]
@mkozjak, is your problem fixed with the new version?

**Comment by mkozjak** [comment]
@stanislas-m: Don't have any time available to test this, as I've moved to other projects atm, but it seems related to the mentioned issue, so this should be resolved, yes!

**Comment by stanislas-m** [comment]
@mkozjak Thanks!
@markbates You can close this one, then. :)
