### ISSUE TITLE
introduce dep for vendor management

### ISSUE THREAD

**Issue by mkozjak** [markbates/pop#90]
We should be able to install and manage `pop` versions via `dep`, the soon-to-be integrated package manager in golang.

**Comment by markbates** [comment]
Not sure I understand the issue. Pop uses semantic versioning, so it works correctly with tools like `dep` already. Also, it is considered bad practice to use vendoring with libraries. Can you shed a bit more light on this issue?

**Comment by mkozjak** [comment]
`go get`ting pop's dependencies is not fancy anymore. `pop` has dependencies, and those should be tracked with `dep`. As far as I'm concerned, all libraries depending on 3rd party libraries should be vendored.
Check US21 [here](https://docs.google.com/document/d/1wT8e8wBHMrSRHY4UF_60GCgyWGqvYye4THvaDARPySs/edit).

ie., you have `github.com/spf13/cobra`. Instead of `go get github.com/spf13/cobra`, we should be able to just `dep ensure -update`.
