### ISSUE TITLE
fizz: foreign key?

### ISSUE THREAD

**Issue by viktorbenei** [markbates/pop#93]
Maybe I missed something but it seems fizz does not have support for declaring foreign keys. Is there a reason? I believe all supported databases support foreign key constraints, but I might be wrong.

**Comment by markbates** [comment]
You can definitely add indexes and you can also execute raw sql, but there isn't direct support for for foreign keys. The reason there isn't is no one has added it yet. It would be a great addition if one was inclined to write a PR. :)

**Comment by viktorbenei** [comment]
Awesome, if there's no blocker I might try to make some time to implement this, although I probably won't have the time in the near future.. Thanks @markbates ! :)

**Comment by markbates** [comment]
Feel free and have a go at it when you have time. The work around is to use the 'raw' function in fizz to add it.

**Comment by markbates** [comment]
https://github.com/gobuffalo/buffalo/issues/670

**Comment by markbates** [comment]
The https://github.com/markbates/pop (v3.x) repo has been moved to https://github.com/gobuffalo/pop (v4.x). The markbates/pop repo has been put into READ-ONLY mode and will no longer be updated. You may continue to use this repository, but be aware no more updates will be made on it.

If this is issues is still relevant, please open a new issue on the repository.

For more information on this move see https://github.com/markbates/pop/issues/164

Thank you so much and I apologize in advance for any trouble this may cause you.
